imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: admin/ }
# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    app.path.ppi_images: /uploads/base/images
    app.path.product_images: /uploads/images/products
    app.path.user_contracts: /uploads/files/user/contracts
    app.path.user_images: /uploads/files/user/images

framework:
    #esi:             ~
    translator:      { fallbacks: ['%locale%', 'en'] }
    secret:          '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  '%locale%'
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        url: '%database_url%'
        charset:  UTF8
        server_version: 5.6
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
          gedmo_tree:
            type: annotation
            prefix: Gedmo\Tree\Entity
            dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
            alias: GedmoTree # this one is optional and will default to the name set for the mapping
            is_bundle: false


# File Uploader
vich_uploader:
    db_driver: orm
    mappings:
        product_images:
            uri_prefix: '%app.path.product_images%'
            upload_destination: '%kernel.root_dir%/../web/uploads/images/products'
        user_images:
          uri_prefix: '%app.path.user_images%'
          upload_destination: '%kernel.root_dir%/../web/uploads/images/products'
        user_contracts:
            uri_prefix: '%app.path.user_contracts%'
            upload_destination: '%kernel.root_dir%/../web/uploads/files/user/contracts'
        base_images:
            uri_prefix: '%app.path.ppi_images%'
            upload_destination: '%kernel.root_dir%/../web/uploads/base/images'
            namer:
                service: vich_uploader.namer_uniqid

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
      address: you@example.com
      sender_name: You
twig:
    form_themes:
            - BnbcUploadBundle:Form:fields.html.twig

swiftmailer:
    transport: null
    host:      null
    username:  null
    password:  null
    spool:     { type: memory }

stof_doctrine_extensions:
    orm:
        default:
            tree: true
