# This file sets the configuration of the 'Category' entity.
#
# NOTE: this demo application splits the backend configuration into several
# small files for educational purposes. In your application you can put the
# entire backend configuration in just one file.
#
# The configuration options are explained in detail in the bundle documentation,
# which is published at https://github.com/javiereguiluz/EasyAdminBundle
easy_admin:
    entities:
        Category:
            class: AppBundle\Entity\Category
            label: 'Categories'
            list:
                title: 'Product %%entity_label%%'
                actions:
                    - { name: 'show', label: '', icon: 'search' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }
                fields:
                    - { property: 'id', , type_options: { disabled: true }}
                    - { property: 'name', label: 'Label' }
                    - { property: 'parent', label: 'Parent category' }
                    - 'products'
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-10', label: 'Category details', icon: 'pencil' }
                    - { property: 'id', , type_options: { disabled: true }}
                    - { property: 'name', label: 'Label' }
                    - { property: 'parent', type: 'Yavin\Symfony\Form\Type\TreeType',  type_options: { class: 'AppBundle\Entity\Category', levelPrefix: ' -  ', orderFields: {lft: 'asc'}, prefixAttributeName: 'data-level-prefix', treeLevelField: 'lvl', by_reference: false  }}

