easy_admin:
    entities:
        Location:
            class: AppBundle\Entity\Location
            controller: AppBundle\Controller\Admin\LocationController
            label: 'Locations'
            list:
                title: '%%entity_label%%'
                actions:
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }
                fields:
                    - 'id'
                    - { property: 'name', label: 'Label' }
                    - { property: 'parent', label: 'Parent category' }
                    - 'products'
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-6', label: 'Basic Details', icon: 'pencil' }
                    - { property: 'id', , type_options: { disabled: true }}
                    - { property: 'name', label: 'Label' }
                    - { property: 'description', type: 'ckeditor' }
                    - { property: 'url' }
                    - { property: 'props', type: 'easyadmin_autocomplete', label: 'Products' }
                    - { property: 'amenityFeature' }
                    - { property: 'event' }
                    - { property: 'faxNumber' }
                    - { property: 'maximumAttendeeCapacity' }
                    - { property: 'openingHoursSpecification' }
                    - { property: 'address' }
                    - { property: 'addressCountry', label: 'County' }
                    - { property: 'globalLocationNumber' }
                    - { property: 'parent', type: 'easyadmin_autocomplete', label: 'Parent location' }
                    - { type: 'group', css_class: 'col-sm-6', label: 'Additional Details', icon: 'cube' }
                    - { property: 'alternateName' }
                    - { property: 'disambiguatingDescription', type: 'ckeditor' }
                    - { property: 'image', type: 'Glavweb\UploaderDropzoneBundle\Form\ImageType', type_options: { label: 'Image', context: 'entity_images', by_reference: false  }}
                    - { property: 'branchCode' }
                    - { property: 'containedInPlace' }
                    - { property: 'containsPlace' }
                    - { property: 'elevation' }
                    - { property: 'latitude' }
                    - { property: 'longitude' }
                    - { property: 'postalCode' }
                    - { property: 'hasMap', label: 'Map' }
                    - { property: 'isicV4' }
                    - { property: 'review' }
                    - { property: 'smokingAllowed' }
                    - { property: 'locationContactName' }
                    - { property: 'locationContactPhone' }
                    - { property: 'locationContactEmail' }