easy_admin:
    entities:
        Product:
            class: AppBundle\Entity\Product
            label: 'PPI Products'
            list:
                actions:
                  - { name: 'edit', label: '', icon: 'edit' }
                  - { name: 'delete', label: '', icon: 'trash' }
                fields:
                    - id
                    - name
                    - alternateName
                    - { property: description, template: '@App/ckeditor_text.html.twig' }
                    - cost
                    - disambiguatingDescription
                    - url
                    - provisionContactName

            show:
                fields:
                    - id
                    - { property: 'logo', type: 'image', base_path: '%app.path.ppi_images%' }
                    - { property: 'name', css_class: 'large' }
                    - description
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-6', label: 'Product details', icon: 'pencil' }
                    - { property: 'id', type_options: { disabled: true }}
                    - { property: 'name'}
                    - { property: 'description', type: 'ckeditor' }
                    - { type: 'divider' }
                    - { property: 'alternateName' }
                    - { property: 'disambiguatingDescription', type: 'ckeditor' }
                    - { property: 'cost', type: 'number' }
                    - { property: 'categories', type: 'easyadmin_autocomplete' }
                    - { type: 'group', css_class: 'col-sm-6', label: 'Additional info', icon: 'info' }
                    - { property: 'mainEntityOf' }
                    - { property: 'potentialAction' }
                    - { property: 'sameAs' }
                    - { property: 'url' }
                    - { property: 'additionalProperty' }
                    - { property: 'aggregateRating' }
                    - { property: 'audience' }
                    - { property: 'image', type: 'Glavweb\UploaderDropzoneBundle\Form\ImageType', type_options: { label: 'Logo', context: 'entity_images', by_reference: false  }}
                    - { property: 'images', type: 'Glavweb\UploaderDropzoneBundle\Form\ImageCollectionType', type_options: { label: 'Product Images', context: 'entity_images', by_reference: false  }}
                    - { property: 'purchaseWorkflow', type: 'choice', type_options: { multiple: false, choices: { 'ORDERED': 'Ordered', 'DELIVERED': 'Delivered' } } }
                    - { property: 'deliveryDate', display_as: datepicker }
                    - { type: 'group', css_class: 'col-sm-6', label: 'Provision info', icon: 'info-circle' }
                    - { property: 'provision', type: 'checkbox', css_class: 'switch-change' }
                    - { property: 'location' }
                    - { property: 'provisionContactName' }
                    - { type: 'divider' }
                    - { property: 'provisionContactPhone' }
                    - { property: 'provisionContactEmail' }
                    - { property: 'gtin8', type_options: { required: true } }
                    - { type: 'divider' }
                    - { property: 'isAccessoryOrSparePartFor', type: 'easyadmin_autocomplete' }
                    - { property: 'isConsumableFor', type: 'easyadmin_autocomplete' }
                    - { property: 'isSimilarTo', type: 'easyadmin_autocomplete' }
#                    - { type: 'section', label: 'Advanced Settings', icon: 'warning', help: 'Reserved for administrators use' }
#                    - { property: 'createdAt' }
#                    - { type: 'group', css_class: 'col-sm-8 new-row' }
                    - { property: 'award' }
                    - { type: 'group', css_class: 'col-sm-6', label: 'Product info', icon: 'info' }
                    - { property: 'brand' }
                    - { property: 'color' }
                    - { property: 'depth' }
                    - { property: 'height' }
                    - { property: 'gtin12' }
                    - { property: 'material' }
                    - { property: 'mpn' }
                    - { property: 'offers' }
                    - { property: 'review' }
                    - { property: 'weight' }
                    - { property: 'width' }
