easy_admin:
    entities:
        Project:
            class: AppBundle\Entity\Project
            controller: AppBundle\Controller\Admin\ProjectController
            label: 'Projects'
            list:
                title: '%%entity_label%%'
                actions:
                    - { name: 'show', label: '', icon: 'search' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }
                fields:
                    - 'id'
                    - { property: 'name', label: 'Name' , template: '@App/table_text.html.twig'}
                    - { property: 'url',  label: 'Url' , template: '@App/table_text.html.twig'}
                    - { property: 'description',  label: 'Description', template: '@App/ckeditor_text.html.twig' }
                    - 'directors'
                    - 'cost'
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-6', label: 'Basic Details', icon: 'pencil' }
                    - { property: 'id', type_options: { disabled: true }}
                    - { property: 'name', label: 'Name' }
                    - { property: 'url',  label: 'Url' }
                    - { type: 'group', css_class: 'col-sm-6', label: 'Additional Details', icon: 'film' }
                    - { property: 'alternateName',  label: 'Alternate name' }
                    - { property: 'disambiguatingDescription',  label: 'Disambiguating Description' }
                    - { property: 'directors', type: 'easyadmin_autocomplete', css_class: 'directors_disable', label: 'Directors', type_options: {  by_reference: false } }
                    - { type: 'group', css_class: 'col-sm-12', label: 'Info', icon: 'cube' }
                    - { property: 'description', type: 'ckeditor', label: 'Description', type_options: { required: true }}
                    - { property: 'summary',  type: 'ckeditor' , label: 'Summary'}
