easy_admin:
    entities:
        Role:
            class: AppBundle\Entity\Role
            label: 'Roles'
            list:
                title: '%%entity_label%%'
                actions:
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }
                fields:
                    - 'id'
                    - { property: 'name', label: 'Name' , template: '@App/table_text.html.twig'}
                    - { property: 'actor', label: 'Actor' , template: '@App/table_text.html.twig'}
                    - { property: 'description',  label: 'Description', template: '@App/ckeditor_text.html.twig' }
                    - { property: 'hobby', label: 'Hobby', template: '@App/ckeditor_text.html.twig'}
                    - 'cost'
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-6', label: 'Basic Details', icon: 'pencil' }
                    - { property: 'id', type_options: { disabled: true }}
                    - { property: 'name',                       label: 'Name'}
                    - { property: 'description',                type: 'ckeditor', label: 'Description' }
                    - { property: 'disambiguatingDescription',  label: 'Disambiguating Description' }
                    - { property: 'url',                        label: 'Url' }
                    - { property: 'appearance',                 type: 'ckeditor' , label: 'Appearance' }
                    - { type: 'group', css_class: 'col-sm-6',   label: 'Additional Details', icon: 'cube' }
                    - { property: 'alternateName',              label: 'Alternate name' }
                    - { property: 'language' }
                    - { property: 'hobby',                      type: 'ckeditor' , label: 'Hobby' }
                    - { property: 'actor',                      label: 'Actor' }
                    - { property: 'age',                        label: 'Age' }
                    - { property: 'countryOfOrigin' }
                    - { property: 'agentCompany' }
                    - { property: 'gender',                     type: 'choice', type_options: { multiple: false, choices: { 'MALE': 'Male', 'FEMALE': 'Female' } } }
                    - { property: 'outfits',                    type: 'easyadmin_autocomplete', label: 'Outfits' }
                    - { type: 'group', css_class: 'col-sm-12', label: 'Media', icon: 'cube' }
                    - { property: 'image', type: 'Glavweb\UploaderDropzoneBundle\Form\ImageType', type_options: { label: 'Image', context: 'entity_images', by_reference: false  }}
                    - { property: 'trailerFile',                type: 'vich_image', label: 'Trailer' }



