easy_admin:
    entities:
        Role:
            class: AppBundle\Entity\Role
            label: 'Roles'
            list:
                title: '%%entity_label%%'
                actions:
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }
                fields:
                    - 'id'
                    - { property: 'name', label: 'Name' , template: '@App/table_text.html.twig'}
                    - { property: 'actor', label: 'Actor' , template: '@App/table_text.html.twig'}
                    - { property: 'description',  label: 'Description', template: '@App/table_text.html.twig' }
                    - { property: 'hobby', label: 'Hobby' , template: '@App/table_text.html.twig'}
                    - { property: 'imageFile', type: 'image', base_path: '%app.path.ppi_images%' }
                    - { property: 'trailerFile', type: 'image', base_path: '%app.path.ppi_images%' }
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-6', label: 'Basic Details', icon: 'pencil' }
                    - id
                    - { property: 'name',                       label: 'Name'}
                    - { property: 'description',                type: 'ckeditor', label: 'Description', css_class: 'large' }
                    - { property: 'url',                        label: 'Url' }
                    - { property: 'actor',                      label: 'Actor' }
                    - { property: 'age',                        label: 'Age'}
                    - { property: 'countryOfOrigin' }
                    - { property: 'agentCompany' }
                    - { property: 'appearance',                 type: 'ckeditor' , label: 'Appearance' }
                    - { property: 'gender',                     type: 'choice', type_options: { multiple: false, choices: { 'MALE': 'Male', 'FEMALE': 'Female' } } }
                    - { property: 'outfits',                    type: 'easyadmin_autocomplete', label: 'Outfits' }
                    - { type: 'group', css_class: 'col-sm-6', label: 'Additional Details', icon: 'cube' }
                    - { property: 'alternateName',              label: 'Alternate name'}
                    - { property: 'disambiguatingDescription',  label: 'Disambiguating Description' }
                    - { property: 'imageFile',                  type: 'vich_image', label: 'Image' }
                    - { property: 'trailerFile',                type: 'vich_image', label: 'Trailer', template: 'video.html.twig' }
                    - { property: 'hobby',                      type: 'ckeditor' , label: 'Hobby' }
            new:
                fields:
                    - '-id'
            edit:
                fields:
                    - { property: 'id', , type_options: { disabled: true }}
                    - { property: 'language' }


