easy_admin:
    entities:
        Scene:
            class: AppBundle\Entity\Scene
            label: 'Scenes'
            list:
                title: '%%entity_label%%'
                actions:
                    - { name: 'show', label: '', icon: 'search' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }
                fields:
                    - 'id'
                    - { property: 'name', label: 'Label' }
                    - { property: 'parent', label: 'Parent category' }
                    - 'products'
            show:
                fields:
                    - 'id'
#                    - { property: 'name', label: 'Label', css_class: 'large' }
#                    - { property: 'parent', label: 'Parent category' }
#                    - 'products'
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-6', label: 'Basic Details', icon: 'pencil' }
                    - id
                    - { property: 'name', label: 'Label', css_class: 'large', help: 'As displayed on the website (the slug is auto-generated)' }
                    - { property: 'description', type: 'ckeditor' }
                    - { property: 'project', type: 'easyadmin_autocomplete' }
                    - { property: 'location', type: 'easyadmin_autocomplete' }
                    - { property: 'subLocations', type: 'easyadmin_autocomplete' }
                    - { property: 'roles', type: 'easyadmin_autocomplete' }
                    - { type: 'group', css_class: 'col-sm-6', label: 'Additional Details', icon: 'cube' }
                    - { property: 'url' }
                    - { property: 'alternateName' }
                    - { property: 'disambiguatingDescription', type: 'ckeditor' }
                    - { property: 'summary', type: 'ckeditor' }
            new:
                fields:
                    - '-id'
            edit:
                fields:
                    - { property: 'id', , type_options: { disabled: true }}
