---
# Set the version of Node.js to install ("0.10", "0.12", "4.x", "5.x", "6.x").
# Version numbers from Nodesource: https://github.com/nodesource/distributions
nodejs_version: "7.x"

# The user for whom the npm packages will be installed.
# nodejs_install_npm_user: username

# The directory for global installations.
npm_config_prefix: "/usr/local/lib/npm"

# Set to true to suppress the UID/GID switching when running package scripts. If set explicitly to false, then installing as a non-root user will fail.
npm_config_unsafe_perm: "false"

# Define a list of global packages to be installed with NPM.
nodejs_npm_global_packages:
   - name: uglify-js
   - name: uglifycss
   - name: ember-cli
   - name: bower
   - name: webpack
   - name: twig